### ISSUE TITLE
select * via parameters

### ISSUE THREAD

**Issue by jardakotesovec** [mfenniak/pg8000#110]
I am using pg8000 with sqlalchemy and I am getting error for statement:

```
        s_count = select([func.count("*")]).select_from('images')
```

```
sqlalchemy.exc.ProgrammingError: (pg8000.core.ProgrammingError) ('ERROR', '42P18', 'could not determine data type of parameter $1', 'postgres.c', '1356', 'exec_parse_message', '', '') [SQL: 'SELECT count(%s) AS count_1 \nFROM user_files'] [parameters: ('*',)]
```

Seems that '*' can't be passed as parameter? It works fine for other adapter I have been using (sqlite, mysql).

Any hint appreciated. Thank you.

**Comment by tlocke** [comment]
Hi @jardakotesovec, it seems like SQLAlchemy is emitting the SQL:

`SELECT count(%s) AS count_1 \nFROM user_files`

but you need to get it to emit:

`SELECT count(cast(%s as varchar)) AS count_1 \nFROM user_files`

the cast to varchar is necessary because pg8000 sends strings as an unknown type and lets PostgreSQL infer the type from the context. This usually works but sometimes you need to do an explicit cast.

**Comment by jardakotesovec** [comment]
@tlocke Thanks for feedback. Meanwhile I managed to make it work with psycopg2 adapter which also does not require explicit casting for this query.

Feel free to close it if thats something you don't want to change.
