### ISSUE TITLE
Cannot pass a generator expression to cursor.insert()

### ISSUE THREAD

**Issue by andrew-tipton-cgg** [mfenniak/pg8000#120]
So it turns out that passing using a generator expression to supply parameters to `cursor.insert()` fails in a spectacular and unexpected manner.  Here is a minimal test case that triggers the bug:

```
# we've set pg8000.paramstyle to 'qmark'
sql = 'INSERT INTO test (a, b, c, d) VALUES (?, ?, ?, ?)'
cursor.execute(sql, args=(i+1 for i in range(4)))
```

And this is the exception that is raised when executed:

```
pg8000.core.ProgrammingError: ('ERROR', '08P01', 'insufficient data left in message', 'pqformat.c', '574', 'pq_copymsgbytes')
```

After pulling my hair out for several hours -- and learning quite a lot about the Postgres protocol in the process -- the error is a result of pg8000 sending a malformed BIND message.  For some reason, it doesn't send the parameter values AT ALL.

**Comment by mfenniak** [comment]
Hi Andrew.  Thanks for reporting this.  My initial thought here is that pg8000 isn't able to identify the correct type to send in it's bind message because the argument is a generator.  This is definitely a pg8000 bug.

I'll be honest with you, I don't have the time right now to look into this and fix it, as much as I'd like to.  I'd be happy to review, advise, and incorporate a patch if you can come up with one.  The core of the problem is probably in make_params; a good start point would be to identify what it's thinking when it receives a generator, and then how that can be tweaked so that it behaves similarly to the array logic.

**Comment by tlocke** [comment]
Rather than doing:

`cursor.execute(sql,` args=(i+1 for i in range(4)))`

it should work if you do:

`cursor.execute(sql, args=list(i+1 for i in range(4)))`

so rather than passing in a generator as an argument, you need to give it a sequence or mapping. This is part of the DB-API standard https://www.python.org/dev/peps/pep-0249/#id14.
