### ISSUE TITLE
Error: unpack_from requires a buffer of at least 5 bytes

### ISSUE THREAD

**Issue by emirot** [mfenniak/pg8000#150]
Any idea why we have this issue : `error: unpack_from requires a buffer of at least 5 bytes`

It's related to : https://github.com/awslabs/amazon-redshift-utils/issues/239

**Comment by tlocke** [comment]
Hi @emirot, this happens when the 5 bytes that pg8000 is expecting aren't available to be read from the socket. Usually this is because there's a network problem and a partial message is received. However, I suppose it could be bug in pg8000 caused by it not fully reading the previous message somehow.
