### ISSUE TITLE
Support for CircleCI 1.0 coming to an end

### ISSUE THREAD

**Issue by tlocke** [mfenniak/pg8000#166]
Support for [CircleCI 1.0](https://circleci.com/sunset1-0/) is coming to an end so I had a go at moving to CircleCI 2.0, but hit problems. I had more success with TravisCI and [have the tests working](https://travis-ci.org/tlocke/pg8000/builds/421513101) against a matrix of Python and PostgreSQL versions with a fairly simple [config file](https://github.com/tlocke/pg8000/blob/master/.travis.yml). So I propose going with TravisCI unless anyone has any objections?

@mfenniak, as the admin of https://github.com/mfenniak/pg8000, could you activate TravisCI and deactivate CircleCI please? Thanks!(alternatively, I'm happy for https://github.com/tlocke/pg8000 to be the official repo if that's easier for you). Also, while we're at it, the repo description needs to be updated to remove the link http://pythonhosted.org/pg8000/, because the docs are the README now.

**Comment by williamjmorenor** [comment]
Hello, currently test are failing in Circle because the pytz library is missing and required here:

https://github.com/mfenniak/pg8000/blob/master/tests/test_typeconversion.py

The dependeny is listed here: https://github.com/mfenniak/pg8000/blob/master/tox.ini#L19 but Circle Ci is no catching it.

The plan is keep using circleci or move to travis?

**Comment by tlocke** [comment]
Hi @williamjmorenor, we've moved to Travis now, and I've made https://github.com/tlocke/pg8000/ the main repository. The reason for moving the repo is that admin access was needed to make the change to Travis.
