### ISSUE TITLE
pg8000.errors.ProgrammingError: ('ERROR', '34000', 'portal "pg8000_portal_1" does not exist')

### ISSUE THREAD

**Issue by raould** [mfenniak/pg8000#39]
I'm getting this with 1.9.9, please let me know any thoughts you have on how i'm using the library wrong, to end up with this. Note that my script runs for quite a while doing many db calls, before it hits this. So to me subjectively it feels like something where pg8000 is getting itself confused after a while. I tried doing shorter transactions, but that didn't seem to help. Thanks very much for any guidance!

  File "/usr/local/lib/python2.7/dist-packages/pg8000/core.py", line 658, in fetchmany
    islice(self, self.arraysize if num is None else num))
  File "/usr/local/lib/python2.7/dist-packages/pg8000/six.py", line 441, in next
    return type(self).**next**(self)
  File "/usr/local/lib/python2.7/dist-packages/pg8000/core.py", line 2044, in **next**
    self.c.handle_messages(self)
  File "/usr/local/lib/python2.7/dist-packages/pg8000/core.py", line 1619, in handle_messages
    raise error
pg8000.errors.ProgrammingError: ('ERROR', '34000', 'portal "pg8000_portal_1" does not exist')

**Comment by tlocke** [comment]
We haven't had any more reports of this, so I'll tentatively mark it as closed. Please do re-open if you come across it again.

**Comment by bobbyi** [comment]
I encountered this issue recently with the current version of pg8000. It can happen if you execute a query, then call commit(), then do fetchall() on the cursor for the result of the query and the result set is sufficiently large. It happens because cursors aren't held open on commit unless the client asks for them to be:

https://www.postgresql.org/message-id/44B029D6.9000807@opencloud.com

**Comment by tlocke** [comment]
Thanks @bobbyi I didn't know about the option of holding the portal open through a commit. I've re-opened the issue and I'll look into it.

**Comment by tlocke** [comment]
I've had a look into this, and as far as I can make out, cursors exist at the SQL level while portals are at the protocol level. So cursors are defined in the SQL standard:

https://www.postgresql.org/docs/9.5/static/sql-declare.html

but portals are specific to postgres and are part of the front end / back end protocol. So while you can specify that a cursor should be held open over transactions, you can't specify that a portal can be held open. If you want to use cursors you can do with pg8000 using the SQL statements DECLARE and FETCH in the normal way. I hope I've got that right, please correct me if not :-)

**Comment by bobbyi** [comment]
Those are server-side cursors. The code I have that was failing does not (I think) use server side cursors. The message thread I linked actually is talking about server-side cursors as well, so it may not be relevant to what I saw. Sorry for the confusion.

I had the following code:

db = pg8000.connect(...)
c = db.cursor() # client-side cursor
c.execute(sql)
db.commit()
return c.fetchall()

This fails with pg8000 but works if the connect() line is changed to use psycopg2. (I didn't actually need the commit() at all, so I removed that and it fixed the problem in my case).

Does pg8000 actually create a server-side cursor given this code? If so, it would explain the behavior difference. psycopg2 creates a client-side cursor if no name is given, which means the result set is still waiting on the client-side after the commit:

http://initd.org/psycopg/docs/connection.html#connection.cursor

**Comment by tlocke** [comment]
Let's call a cursor created with the DECLARE SQL statement an 'SQL cursor'. With this definition, pg8000 doesn't use SQL cursors. The reason the code above fails with pg8000 is that when a query is executed the results are retrieved in batches from a so called 'named portal' that is open on the db server. The portal is part of the PostgreSQL protocol see:

https://www.postgresql.org/docs/current/static/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

a portal doesn't survive a commit, so in the code above when the fetchall() method is called pg8000 goes back to the portal but finds it doesn't exist any more because it's been closed by the commit. So pg8000 gives the error you originally reported:

     portal "pg8000_portal_1" does not exist'

psycopg also uses portals (as all drivers must) but when it's using unnamed cursors it always retrieves all the rows from the portal on the execute*() methods, that's why the code example you give works for psycopg.

**Comment by tlocke** [comment]
I've added a common way that this error arises at:

https://github.com/mfenniak/pg8000#i-m-getting-a-portal-pg8000_portal_1-does-not-exist-error
