### ISSUE TITLE
Json data type

### ISSUE THREAD

**Issue by ilvalle** [mfenniak/pg8000#68]
Is json data type going to be supported?

**Comment by tlocke** [comment]
A way of making pg8000 support JSON would be to do something like:

    val = {'name': 'Apollo 11 Cave', 'zebra': True, 'age': 26.003}
    self.cursor.execute("SELECT cast(%s as json)", (json.dumps(val),))
    retval = self.cursor.fetchall()
    self.assertEqual(retval[0][0], val)

so the application would be responsible for turning the JSON into a string with json.dumps() to send as a parameter but pg8000 would return a de-serialized result. I'll get going on coding that, but let me know if you have any thoughts / ideas.

**Comment by tlocke** [comment]
I've committed this at https://github.com/mfenniak/pg8000/commit/cdddb94edd1dd97f2e869985405b388e1e7c6298

**Comment by tlocke** [comment]
Realized I missed out the jsonb type that came out in postgres 9.4 so I've added that at https://github.com/mfenniak/pg8000/commit/6d2d87c4c09873e3057a5c5152b6870933700efc.

**Comment by mfenniak** [comment]
It seems pretty strange that the input and output formats for the driver would be completely different (a string of JSON text versus an object).  This seems like it would be awkward to use, wouldn't it?  It also seems like there'd be an ambiguity in reading a json or jsonb type from Postgres that contains "null"; this is distinct from a NULL value in Postgres, but both values would be converted into None.

What if the driver supplied a wrapper object type that would "mark" a Python object as something that we will convert to and from json?  eg. pg8000.JSON(obj) would result in json.dumps(obj) being run on that object when sent to the server, and a pg8000.JSON type would be returned from a query that returned a JSON object.  A simple API like having a "value" property would return the value of the JSON from json.loads(...).

**Comment by tlocke** [comment]
I think JSON is different to most other data types because the user needs access to both the serialized form (string) and the de-serialized form (Python objects). This is in contrast to, say, an ``int`` where the user never wants to see the serialized form.

So the user of pg8000 may want to send the JSON as a string or as an object, and may want to receive the JSON as a string or as an object. Under my proposal, the four ways would be:

    # assume a table t with json column val

    # send json serialized, return json serialized
    self.cursor.execute("SELECT cast(val as text) from t where val = %s", ('{"age": 43}',))

    # send json serialized, return json de-serialized
    self.cursor.execute("SELECT val from t where val = %s", ('{"age": 43}',))

    # send json de-serialized, return json serialized
    self.cursor.execute("SELECT cast(val as text) from t where val = %s", ({'age': 43},))

    # send json de-serialized, return json de-serialized
    self.cursor.execute("SELECT val from t where val = %s", ({'age': 43},))

I think that's fairly intuitive. If I've understood correctly, writing the examples above using a pg8000.JSON class would give:

    # assume a table t with json column val

    # send json serialized, return json serialized
    self.cursor.execute("SELECT cast(val as text) from t where val = %s", (JSON('{"age": 43}'),))

    # send json serialized, return json de-serialized
    self.cursor.execute("SELECT val from t where val = %s", (JSON('{"age": 43}',)))
    # then obj.value()

    # send json de-serialized, return json serialized
    self.cursor.execute("SELECT cast(val as text) from t where val = %s", (JSON({'age': 43}),))

    # send json de-serialized, return json de-serialized
    self.cursor.execute("SELECT val from t where val = %s", (JSON({'age': 43}),))
    # then obj.value()

Which isn't as nice in my opinion.

I think you're right about the SQL ``NULL`` and the JSON ``null``, and not being able to tell the difference. I hadn't thought of that. My response would be that you could always return the json as a string, check for None and then use json.loads() ?
