### ISSUE TITLE
RESPONSE_WHERE in error reporting

### ISSUE THREAD

**Issue by aek** [mfenniak/pg8000#72]
It could be helpful if the method handle_ERROR_RESPONSE put in the ProgrammingError exception the RESPONSE_WHERE value of the msg_dict if available even when it's easy to hack to get it. 
This is for example the case of an exception caused by a errors in the data stream used for sql copy using STDIN as copy input. In this case the RESPONSE_WHERE value of the msg_dict holds the line of the copy data that have errors, and it's useful for error reporting and to ignore that line and resend the copy sql again.
I resolve this in my code by replacing the handle_ERROR_RESPONSE in the connection instance message_types[ERROR_RESPONSE] value with a new one that allow me to get the need error value. 

This is what I mean:
```python
conn = DBAPI.connect('postgres',host="localhost", database='example', password='admin')

def handle_patch_ERROR_RESPONSE(data, ps):
    msg_dict = data_into_dict(data)
    if msg_dict[RESPONSE_CODE] == "28000":
        raise InterfaceError("md5 password authentication failed")
    else:
        error = ProgrammingError(
            msg_dict[RESPONSE_SEVERITY], msg_dict[RESPONSE_CODE],
            msg_dict[RESPONSE_MSG])
        if msg_dict.get(RESPONSE_WHERE, False):
            error.message = msg_dict[RESPONSE_WHERE]
        raise error
conn.message_types[ERROR_RESPONSE] = handle_patch_ERROR_RESPONSE
```
See the new if to add the RESPONSE_WHERE value of msg_dict when available. I can submit a pull request with this little change.

**Comment by tlocke** [comment]
I've put a commit in my repo at https://github.com/tlocke/pg8000/commit/4a00866f637ad5cff28630ba5361d65fb4ccefba which should solve this. It takes the approach of constructing the ProgrammingError from all the fields that are sent. If we're happy with it I'll push it to the main repo.

**Comment by aek** [comment]
That seems to be a solution but it would be better if the ProgrammingError exception fields could be getted by name as a properties. something like:
'''
try:
    cursor.execute(copy_sql, stream=handler)
except (DatabaseError, ProgrammingError), e:
    print e.where
''''
Also I notices that you remove the raise of the exception and now the error is asigned to self.error in my local version installed from pypi in that method, the error is raised

**Comment by tlocke** [comment]
Hi @aek, to answer your second question first:

> Also I notices that you remove the raise of the exception and now the error is asigned to self.error in my local version installed from pypi in that method, the error is raised

We can't raise the exception straight away, because of how the Postgres protocol works. The client (in this case pg8000) has to keep handling messages from the server even after the ERROR_RESPONSE has been received. In fact it keeps reading messages until  a READY_FOR_QUERY message is received. You can see this in the handle_messages function.

Your second question was about getting the parts of server error messages by name, as exception attributes. I'm not sure about this because the ProgrammerError class covers more cases than just server errors, in which case all the attributes would be null. As it is, you can get the parts of the message by looking at the args attribute, eg. args[0] for the code. I not against the idea, but I'm not convinced yet either :-)

**Comment by tlocke** [comment]
I think we've gone some way to improving the error reporting here, so I'll close the issue. Feel free to open another issue for further improvements.
