### ISSUE TITLE
minor bug in escaping special characters

### ISSUE THREAD

**Issue by xiaolong** [mfenniak/pg8000#77]
The issue is when I tried to execute a statement that contains `%` within a string, I got the following error:

    '% ' not supported in a quoted string within the query string

The SQL statement I was trying to execute is:
    
    INSERT INTO events(event_type) VALUES ('cars 50% saved');

and this is the Python code segment that fails:

    query = 'insert into events(event_type) values (\'%s\');' % ('cars 50% saved')
    cursor.execute(query)

If I replace `%` with `%%`, it succeeds ---which is weird.

I briefly look at [this line](https://github.com/mfenniak/pg8000/blob/master/pg8000/core.py#L529), and it seems like only 2 consecutive percent sign (`%%`) is treated as percent sign, while a single percent sign (`%`) will throw an exception.  Is there a specific reason to do this? I mean, single percent sign works totally fine with `psql` or GUI tools like `pgAdmin` or `Navicat`.

------------
Edit:
I do realize that I can do it with:

    cursor.execute("insert into events(event_type) values (%s); ", ("cars 50% saved",))

but there is no compelling reason that the previous code should fail.

**Comment by mfenniak** [comment]
Hi @xiaolong, thanks for the bug report.  I'd say this looks like an issue; I'm guessing that if you used %% it would work.  The driver is probably trying to do query formatting here even though you haven't provided any parameters to substitute into the query.

Since there's a workaround possible, I think we won't be jumping on this issue as a really urgent issue that needs to be fixed.  But I still really appreciate the bug report. :-)  Thank-you, and, this issue will get addressed.

**Comment by tlocke** [comment]
Hello, I've come to the conclusion that this isn't a bug, and that we're doing the right thing already. The blanket rule across DB-API drivers (eg. Psycopg2) and libraries (eg. SQLAlchemy) seems to be that % characters need to be escaped with %% (no matter where they appear in the query) if you mean a single %.

So changing the rule for pg8000 would break backward compatibility, and compatibility with other DB-API code and libraries. Regardless of backward compatibility issues, I don't think that allowing single % in literals would be a good idea anyway, better to stick to a simple rule that doesn't have exceptions.

Also, as an aside, while other drivers will let you do parameter substitution within a literal, pg8000 raises an exception. This is the right thing to do, because it's not clear to me what a parameter within a literal actual means.

**Comment by mfenniak** [comment]
Hm, that seems like a reasonable assessment, @tlocke.  I can see an argument to be made that if you're not providing parameters, then the query substitution code doesn't even have to be run... but certainly if anyone is out there double-percent encoding in a query today because of this behavior, changing it would break their code.

The two workarounds available are to either double-percent encode your string if it is a hard-coded SQL query, or use parameter substitution if it is not.

**Comment by ownaginatious** [comment]
Hi there,

I'm getting the same error with the following query:
```
...
AND mpu.email NOT LIKE '%mydomain.com'
...
```

Same with the double quoted variant:
```
...
AND mpu.email NOT LIKE "%mydomain.com"
...
```

Clearly in this context, the `%` is supposed to be interpreted without being escaped. My query works fine in `psql`. Is there a workaround for this, or is this a legitimate issue in `pg8000`?
