### ISSUE TITLE
execute() without prepared statements

### ISSUE THREAD

**Issue by realazthat** [mfenniak/pg8000#84]
Hi, feature request for simple query mode. This allows for multiple statements in a single query.

**Comment by tlocke** [comment]
My view on supporting simple query mode is that the extra complexity of users understanding the two different modes, and the added complexity of the driver code itself, isn't justified, since if you want to execute two statements you can currently just make two calls to 'execute()' which is nice and simple.

**Comment by ssbarnea** [comment]
I have the following problem: I want to run a transaction and now it seems not to be possible with pg8000, due to this.

Example:
```
BEGIN;
DELETE from...;
INSERT INTO ...;
COMMIT;
```

**Comment by tlocke** [comment]
Hi @ssbarnea, I'm probably missing something, but can't you do something like:

    import pg8000
    
    conn = pg8000.connect(user="postgres", password="C.P.Snow")
    cursor = conn.cursor()
    cursor.execute("CREATE TEMPORARY TABLE book (id SERIAL, title TEXT)")
    cursor.execute(
        "INSERT INTO book (title) VALUES (%s), (%s)",
        ("Ender's Game", "Speaker for the Dead"))
    conn.commit()
    cursor.execute("DELETE from book")
    cursor.execute("INSERT INTO book (title) values ('Emma')")
    conn.commit()
