### ISSUE TITLE
commit() in a fetchone loop fails after certain iterations

### ISSUE THREAD

**Issue by ilvalle** [mfenniak/pg8000#90]
In https://github.com/web2py/pydal we are facing an issue using pg8000. An example to reproduce the issue is

```
import pg8000
conn = pg8000.connect(user='web2py', password="web2py", database='test_w2p')

c1 = conn.cursor()
c2 = conn.cursor()

# Create table
c1.execute('''CREATE TABLE t0
             (qty real)''')
c1.execute('''CREATE TABLE t1
             (qty real)''')

for n in xrange(1, 1000, 1):
    c1.execute("INSERT INTO t0 VALUES (%s)" % n)

# Save (commit) the changes
conn.commit()
c1.execute("select * from t0")

ctr=0
while True:
    # Get the next row in the cursor
    row = c1.fetchone()
    if row == None: break

    c2.execute("INSERT INTO t1 VALUES (999)")
    conn.commit()
    ctr += 1

print ctr
conn.close()
```

it works if the table contains 100 items, it fails with 1000items raising

```
pg8000.core.ProgrammingError: (u'ERROR', u'34000', u'portal "pg8000_portal_1004" does not exist', u'postgres.c', u'1860', u'exec_execute_message', u'', u'')
```

Tested with python 2.7.6, pg8000 1.10.2, pg 9.1.18

**Comment by tlocke** [comment]
Hi @ilvalle, I think the problem is with the line:

    c1.execute("INSERT INTO t0 VALUES (%s)" % n)

which I think should be:

    c1.execute("INSERT INTO t0 VALUES (%s)", (n,))

The first way is sending a single statement with the value as part of the string. The second way is using a parametrised statement. The second way is preferred because:

* It avoides SQL injection attacks.
* Since pg8000 creates a new prepared statement for each unique query string that's executed, you quickly reach the maximum number of prepared statements that PostgreSQL can have open.

**Comment by ilvalle** [comment]
@tlocke thanks for the suggestions, however it's still failing. 
The exception is raised by ```c1.fetchone()```

**Comment by tlocke** [comment]
@ilvalle I've managed to reproduce the problem and I've worked out what's going on. The problem is the commit within the loop. If a transaction is committed then Postgres closes all open portals. The cache size in pg8000 is 100, so after it's reached 100 it tries to read from the portal on the server, but finds the portal has been closed because the transaction has ended.

I hope that makes sense. If you did everything in one transaction, then everything would work. Alternatively you could read all the rows from the database in one loop, then insert other rows in a second loop.

**Comment by mfenniak** [comment]
@tlocke - - just want to clarify, are you saying you think it is a valid issue still? The reproduction code provided here probably isn't representative of the app that this error occurred in, so the workaround advice might not be applicable.

It looks like code that should work. The fact that the read cursor is broken by commit on the connection seems like something that shouldn't happen. Not sure what we can actually do about that, though.

**Comment by tlocke** [comment]
I don't think it's a bug, more of a characteristic of postgres. We could change pg8000 so that it always retrieves all the rows returned by a query in one go. Although some people might be relying on the buffering behaviour to efficiently iterate over a large result set when you don't know at the beginning when you're going to stop. Hmm, on balance I think we should keep it as it is for now.

**Comment by ilvalle** [comment]
The code is an example of what it's generated by pydal. The idea is to loop
over an iterator and run/commit operations in the loop.
The example works with other drivers as psycopg on postgres, and other
drivers/backend in general (i.e., mysql).

 Paolo

2015-10-23 0:08 GMT+02:00 Tony Locke <notifications@github.com>:

**Comment by tlocke** [comment]
In general in DB-API, the fetch*() methods may go back to the server. Is it possible to use the fetchall() method in your code, so instead of:

    ctr=0
    while True:
        # Get the next row in the cursor
        row = c1.fetchone()
        if row == None: break

        c2.execute("INSERT INTO t1 VALUES (999)")
        conn.commit()
        ctr += 1

you could have:

    ctr=0
    for row in c1.fetchall():
        c2.execute("INSERT INTO t1 VALUES (999)")
        conn.commit()
        ctr += 1

**Comment by mfenniak** [comment]
I agree with @tlocke.  It's clearly surprising behaviour, and that sucks.  But it makes sense that you can't have an in-progress query (the SELECT) continue operating while committing a transaction on the same connection.  Using ```fetchall``` is one alternative.  Using a separate connection to perform the reads is another alternative.

pg8000's behaviour is unlike other drivers like psycopg here because we don't automatically buffer the entire response of a query when you make it.  We stream the results from the server in small batches, which is more memory-efficient for large queries, but less network-efficient than other drivers.  It also exposes this kind of problem.

I still think there's a problem with pg8000's behaviour though; it's unfortunate that this works for the first 100 rows.  I think pg8000 should raise an exception when you try to read from a cursor after the cursor has been closed, even if there is still buffered data available.  The error could also be clearer and simpler.

**Comment by tlocke** [comment]
I think I've changed my mind on this. I've put a suggested change at:

https://github.com/tlocke/pg8000/commits/master

The change is to always read in all the results in one go. The reasons for doing it are:

* It makes pg8000 simpler because it uses the unnamed portal rather than having to remember portal names and explicitly close them.

* Getting a 'portal closed' exception is really confusing, and with this change you'd never get that exception. Even if you understand what it means to get a 'closed portal' I've found that it's hard to work out why.

* It's a bit faster, because you don't have to do the portal closing or send multiple execute messages, so there's less to and fro between client and server.

The only potential drawback would be memory efficiency. This doesn't seem to be a problem for other drivers, and on the rare occasions where it might matter, it's always possible to do multiple queries.

So there's my case! If there are no objections I'll commit it to the main repo, and also I'll do a release as we haven't had one for a while.

**Comment by mfenniak** [comment]
Hm, I can't say I like this change, @tlocke.  I understand the advantages you're referring to, but it also undermines some of the advantages that pg8000 has today, including streaming result sets, and the ability to have multiple streaming result sets from the same database connection with multiple cursors.  But honestly, there's more of your code in this project today than there is mine, so if you're convinced, I'll trust your choice. :-)

Hm... I'd also be concerned about the impact to any users from pushing out an upgrade with this change.  It would at least warrant a major version bump.

psycopg2 roughly supports both approaches by allowing a cursor to be explicitly named (http://initd.org/psycopg/docs/usage.html#server-side-cursors / http://initd.org/psycopg/docs/connection.html#connection.cursor).  I think it looks like it uses SQL to DECLARE the server-side cursor, though, which is slightly different than a named portal.

I wonder if the best approach here would be to retain what we have, but perhaps not make it the default behaviour.  What would you think about that?

**Comment by tlocke** [comment]
I think I've come down on the side of using the unnamed portal, that is, always reading everything into memory. It's a big change, but my thinking is that we can always revert if people really don't like it.
