### ISSUE TITLE
Feature for not to cache oid of tables?

### ISSUE THREAD

**Issue by jiohyoo** [mfenniak/pg8000#91]
It seems the oid of the table is cached inside of a connection object.
So when there are two separate connections:

conn1: select max(id) from my_table, works okay.
conn2: drop table my_table, create table my_table (...) okay
conn1: re-run the exact same query "select max(id) from my_table" again, then the oid does not exist anymore in the database and raises exception, even though the table called "my_table" exists in the table.

Is there any feature/options to not cache the oid tables? If not, is it okay if I add that option?

**Comment by yoojioh** [comment]
<img width="1428" alt="screen shot 2015-11-09 at 13 44 04pst" src="https://cloud.githubusercontent.com/assets/834632/11050775/e02a084a-86fd-11e5-8704-a6ea00cbec80.png">

**Comment by mfenniak** [comment]
Yes, I agree with you, this is definitely a problem.  A PR to add an option to disable this behaviour would definitely be entertained.

**Comment by mfenniak** [comment]
I actually thought this cache was removed at some point, and, reviewing the code I can't find it either.  There's a vestigial reference to a use_cache parameter to the connection, but it isn't used anywhere in the code base.  Try giving ```master``` a shot and see if this issue still exists?

**Comment by tlocke** [comment]
Hi @yoojioh I've tried to reproduce the problem but haven't  been able to. What version of Postgres are you running?

pg8000 re-uses prepared statements, so the first time you execute a query it creates the prepared statement, but subsequent times it uses the existing one. Dropping and re-creating a table shouldn't be a problem because as it says in the docs:

> ...PostgreSQL will force re-analysis and re-planning of the statement before using it whenever database objects used in the statement have undergone definitional (DDL) changes since the previous use of the prepared statement.

http://www.postgresql.org/docs/current/static/sql-prepare.html

Anyway, I've tried and failed to reproduce the problem with versions 9.1, 9.2, 9.3 and 9.4. If you're using one of these versions, then could you send me an example script that fails? Thanks.
